// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALW_yRT95rb2sTvE4jjWMX7wiX9tYwJMU',
    appId: '1:621284698388:android:da399048281db856dfba01',
    messagingSenderId: '621284698388',
    projectId: 'mataheko-7c9ae',
    storageBucket: 'mataheko-7c9ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALW_yRT95rb2sTvE4jjWMX7wiX9tYwJMU',
    appId: '1:621284698388:ios:16a53a5a7380d18edfba01',
    messagingSenderId: '621284698388',
    projectId: 'mataheko-7c9ae',
    storageBucket: 'mataheko-7c9ae.firebasestorage.app',
    androidClientId: '621284698388-1o7q2tvnpdr6nj2gfatev22043pv9a0n.apps.googleusercontent.com',
    iosClientId: '621284698388-mos9cfcjmm0qt3ei06v96s5utb7ftktm.apps.googleusercontent.com',
    iosBundleId: 'com.mataheko.community',
  );
}
